name: CI

# Control when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Define the jobs
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Lets get Node installed
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      # Install Node project
      - name: Set up project
        run: npm install
      
      # Install Node project
      - name: Run project tests etc 
        run: npm install
